version: 2

jobs:

  app_checkout:
    docker:
      - image: circleci/node:9-stretch-browsers
    working_directory: ~/build
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build

  node_dependencies:
    docker:
      - image: circleci/node:9-stretch-browsers
    working_directory: ~/build
    steps:
      - run:
          name: Install Yarn
          command: |
            sudo npm install -g yarn
            sudo chmod a+x /usr/local/bin/yarn
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Installing NPM Dependencies
          command: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - ~/build/node_modules

  testing:
      docker:
        - image: circleci/node:9-stretch-browsers
      working_directory: ~/build
      steps:
        - restore_cache:
            key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - restore_cache:
            key: v1-deps-{{ checksum "package.json" }}
        - run:
            name: Performing Tests
            command: yarn test
        - run:
            name: Performing Linting
            command: yarn linter

  precompile:
    docker:
      - image: circleci/node:9-stretch-browsers
    working_directory: ~/build
    steps:
      - run:
          name: Install Yarn
          command: |
            sudo npm install -g yarn
            sudo chmod a+x /usr/local/bin/yarn
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Compiling App
          command: yarn build:dist
      - persist_to_workspace:
          root: public
          paths: ./

  deploy_production:
    docker:
      - image: circleci/node:9-stretch-browsers
    working_directory: ~/build
    steps:
      - attach_workspace:
          at: public
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python-pip python-dev jq
            sudo pip install awscli
      - run:
          name: Deploy to S3 PRODUCTION
          command: aws s3 sync public s3://example.com --delete

  deploy_staging:
    docker:
      - image: circleci/node:9-stretch-browsers
    working_directory: ~/build
    steps:
      - attach_workspace:
          at: public
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python-pip python-dev jq
            sudo pip install awscli
      - run:
          name: Deploy to S3 STAGING
          command: aws s3 sync public s3://staging.example.com --delete

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - app_checkout:
          filters:
              branches:
                  only: master
              tags:
                  only: /.*/
      - node_dependencies:
          filters:
              branches:
                  only: master
              tags:
                  only: /.*/
          requires:
            - app_checkout
      - testing:
          filters:
            branches:
                only: master
            tags:
                only: /.*/
          requires:
            - node_dependencies
      - precompile:
          filters:
            branches:
                only: master
            tags:
                only: /.*/
          requires:
            - testing
            - node_dependencies
      - deploy_staging:
          filters:
              branches:
                  only: master
              tags:
                  ignore: /^v.*/
          requires:
            - precompile
      - deploy_production:
          filters:
              branches:
                  ignore: /.*/
              tags:
                  only: /^v.*/
          requires:
            - precompile

